# Generated by Django 3.0.3 on 2020-02-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('energy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CaloriesCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ingredients', models.ManyToManyField(to='caloriestracker.Ingredient')),
            ],
        ),
    ]
