# Generated by Django 3.0.3 on 2020-03-02 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caloriestracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateField()),
                ('number', models.IntegerField()),
                ('mealTitle', models.CharField(max_length=50)),
                ('namesCalories', models.ManyToManyField(to='caloriestracker.Ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
